// `spool plan generate` end to end, and what `spool lint` says about its output.

import test from 'node:test';
import assert from 'node:assert/strict';
import { execFile } from 'node:child_process';
import { mkdtemp, readFile, rm, writeFile } from 'node:fs/promises';
import { existsSync, readFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { promisify } from 'node:util';

const exec = promisify(execFile);
const here = dirname(fileURLToPath(import.meta.url));
const repo = join(here, '..');
const cli = join(repo, 'bin', 'spool.mjs');
const fixtures = join(here, 'fixtures', 'plan');
const fixture = (name) => readFileSync(join(fixtures, name), 'utf8');

async function workdir(files) {
  const dir = await mkdtemp(join(tmpdir(), 'spool-plan-gen-'));
  for (const [name, body] of Object.entries(files)) {
    await writeFile(join(dir, name), typeof body === 'string' ? body : JSON.stringify(body, null, 2));
  }
  return dir;
}

// Explicit style on every run so a developer's ~/.spool.json cannot change the expected
// output, and the model rewrite off so these fixtures stay byte-reproducible on a machine
// that has a key.
async function runCli(args, env = {}) {
  const child = { ...process.env, SPOOL_PLAN_MODEL: 'none', ...env };
  try {
    const { stdout, stderr } = await exec(process.execPath, [cli, ...args], { cwd: repo, env: child });
    return { code: 0, stdout, stderr };
  } catch (e) {
    return { code: e.code ?? 1, stdout: e.stdout ?? '', stderr: e.stderr ?? '' };
  }
}

// The narration register has no flags: a project picks one and keeps it. The env vars
// are the escape hatch, and they are what pins the register for these fixtures.
const generate = (dir, ...rest) =>
  runCli(['plan', 'generate', dir, ...rest], { SPOOL_PLAN_VOICE: 'direct-technical', SPOOL_PLAN_VISUALS: 'code-forward' });

const valid = () => ({ 'plan.json': fixture('valid-full.json'), 'evidence.json': fixture('valid-full.evidence.json') });

test('a workdir with no plan.json is not a Plan Spool', async () => {
  const dir = await workdir({});
  try {
    const r = await generate(dir);
    assert.equal(r.code, 1);
    assert.match(r.stderr, /no plan\.json/);
  } finally {
    await rm(dir, { recursive: true, force: true });
  }
});

test('an invalid packet is refused before any narration is generated', async () => {
  const dir = await workdir({ 'plan.json': fixture('invalid-missing-required.json') });
  try {
    const r = await generate(dir);
    assert.equal(r.code, 1);
    assert.match(r.stderr, /invalid/);
    assert.match(r.stderr, /outcome/);
    assert.equal(existsSync(join(dir, 'plan.script.json')), false);
  } finally {
    await rm(dir, { recursive: true, force: true });
  }
});

test('a valid packet generates plan.script.json with the acceptance chapters', async () => {
  const dir = await workdir(valid());
  try {
    const r = await generate(dir);
    assert.equal(r.code, 0, r.stderr);
    assert.match(r.stdout, /4 chapters/);
    assert.match(r.stdout, /wrote .*plan\.script\.json/);
    const script = JSON.parse(await readFile(join(dir, 'plan.script.json'), 'utf8'));
    assert.deepEqual(script.chapters.map((c) => c.id), ['context', 'approach', 'risks', 'decision']);
    assert.equal(script.generator, 'deterministic');
    assert.ok(script.estimatedSeconds >= 45 && script.estimatedSeconds <= 120);
    assert.ok(script.voice.instructions.length > 0);

    // Regenerating writes the same bytes.
    const first = await readFile(join(dir, 'plan.script.json'), 'utf8');
    await generate(dir);
    assert.equal(await readFile(join(dir, 'plan.script.json'), 'utf8'), first);
  } finally {
    await rm(dir, { recursive: true, force: true });
  }
});

test('--json returns the script and its lint report', async () => {
  const dir = await workdir(valid());
  try {
    const r = await generate(dir, '--json');
    assert.equal(r.code, 0, r.stderr);
    const out = JSON.parse(r.stdout);
    assert.equal(out.ok, true);
    assert.equal(out.script.kind, 'plan-script');
    assert.ok(Array.isArray(out.lint.warnings));
  } finally {
    await rm(dir, { recursive: true, force: true });
  }
});

test('--steps needs a URL, then writes a steps.mjs that lints clean', async () => {
  const dir = await workdir(valid());
  try {
    const missing = await generate(dir, '--steps');
    assert.equal(missing.code, 1);
    assert.match(missing.stderr, /--steps needs an app URL/);

    const r = await generate(dir, '--steps', '--url', 'http://localhost:3000');
    assert.equal(r.code, 0, r.stderr);
    const src = await readFile(join(dir, 'steps.mjs'), 'utf8');
    assert.match(src, /generated by spool plan generate/);
    assert.match(src, /name: "context"/);
    assert.match(src, /name: "decision"/);

    // The URL is remembered from the emitted steps.mjs on the next run.
    const again = await generate(dir, '--steps');
    assert.equal(again.code, 0, again.stderr);

    const lint = await runCli(['lint', dir]);
    assert.equal(lint.code, 0, lint.stdout + lint.stderr);
    assert.match(lint.stdout, /\[plan-script\]/);
    assert.match(lint.stdout, /\[steps\] compiles and validates \(4 steps\)/);
  } finally {
    await rm(dir, { recursive: true, force: true });
  }
});

test('a refused generation writes nothing and says which chapter is missing', async () => {
  const plan = JSON.parse(fixture('valid-full.json'));
  plan.chapters = [{ id: 'context' }, { id: 'approach' }, { id: 'decision' }];
  const dir = await workdir({ 'plan.json': plan, 'evidence.json': fixture('valid-full.evidence.json') });
  try {
    const r = await generate(dir);
    assert.equal(r.code, 1);
    assert.match(r.stderr, /no "risks" chapter/);
    assert.match(r.stderr, /nothing written/);
    assert.equal(existsSync(join(dir, 'plan.script.json')), false);
  } finally {
    await rm(dir, { recursive: true, force: true });
  }
});

test('spool lint reports a tampered script and blocks the workdir', async () => {
  const dir = await workdir(valid());
  try {
    assert.equal((await generate(dir)).code, 0);
    const script = JSON.parse(await readFile(join(dir, 'plan.script.json'), 'utf8'));
    script.chapters.find((c) => c.id === 'decision').card.prompt = 'Ship it.';
    await writeFile(join(dir, 'plan.script.json'), JSON.stringify(script, null, 2));

    const lint = await runCli(['lint', dir]);
    assert.equal(lint.code, 1);
    assert.match(lint.stdout, /plan-script/);
    assert.match(lint.stdout, /decision/);
  } finally {
    await rm(dir, { recursive: true, force: true });
  }
});

test('lint reports an unreadable plan.script.json instead of skipping it', async () => {
  const dir = await workdir({ ...valid(), 'plan.script.json': '{ not json' });
  try {
    const lint = await runCli(['lint', dir]);
    assert.equal(lint.code, 1);
    assert.match(lint.stdout, /plan\.script\.json is not readable JSON/);
  } finally {
    await rm(dir, { recursive: true, force: true });
  }
});

test('a renamed step keeps its chapter: the anchor is chapterId, not the name', async () => {
  const dir = await workdir(valid());
  try {
    await generate(dir, '--steps', '--url', 'http://localhost:3000');
    const src = await readFile(join(dir, 'steps.mjs'), 'utf8');
    await writeFile(join(dir, 'steps.mjs'), src.replace('name: "risks"', 'name: "misc"'));
    const lint = await runCli(['lint', dir]);
    assert.doesNotMatch(lint.stdout, /no step for chapter/);
  } finally {
    await rm(dir, { recursive: true, force: true });
  }
});

test('lint warns when steps.mjs has drifted from the chapters', async () => {
  const dir = await workdir(valid());
  try {
    await generate(dir, '--steps', '--url', 'http://localhost:3000');
    const src = await readFile(join(dir, 'steps.mjs'), 'utf8');
    // The step that carried the "risks" chapter now carries none of it.
    await writeFile(
      join(dir, 'steps.mjs'),
      src.replace('name: "risks",\n    chapterId: "risks",', 'name: "misc",')
    );
    const lint = await runCli(['lint', dir]);
    assert.match(lint.stdout, /no step for chapter\(s\) risks/);
  } finally {
    await rm(dir, { recursive: true, force: true });
  }
});

test('the generated narration is the register the VO layer will read', async () => {
  const dir = await workdir(valid());
  try {
    await runCli(['plan', 'generate', dir], { SPOOL_PLAN_VOICE: 'calm-client-ready', SPOOL_PLAN_VISUALS: 'code-forward' });
    const { planVoiceInstructions } = await import('../src/plan/generate.mjs');
    const instructions = await planVoiceInstructions(dir);
    assert.match(instructions, /calm project lead/);
  } finally {
    await rm(dir, { recursive: true, force: true });
  }
});

test('a non-plan workdir is untouched by the plan-script lint', async () => {
  const dir = await workdir({ 'steps.mjs': 'export const config = { url: "http://x" };\nexport const steps = [{ name: "a", narration: "hi", run: async () => {} }];\n' });
  try {
    const lint = await runCli(['lint', dir]);
    assert.equal(lint.code, 0, lint.stdout);
    assert.doesNotMatch(lint.stdout, /plan-script/);
  } finally {
    await rm(dir, { recursive: true, force: true });
  }
});
