// `spool lint`: fast static checks over a spool workdir (steps.mjs, timeline.json,
// tour.json, vo/manifest.json, diff.patch). No browser launch; exit 1 only on errors.

import { readFile } from 'node:fs/promises';
import { existsSync, readFileSync } from 'node:fs';
import path from 'node:path';
import { pathToFileURL } from 'node:url';
import { validateStepsModule } from '../record/validate.mjs';

const EM_DASH = '\u2014'; // detected character kept as an escape (no literal em dashes in source)
const TOUR_MODES = [null, undefined, 'walkthrough', 'explainer'];

async function readJsonSafe(p) {
  return JSON.parse(await readFile(p, 'utf8'));
}

// File paths named by diff.patch: "diff --git a/x b/y" plus +++/--- headers.
function diffPaths(text) {
  const paths = new Set();
  for (const line of text.split('\n')) {
    const git = line.match(/^diff --git a\/(.+) b\/(.+)$/);
    if (git) { paths.add(git[1]); paths.add(git[2]); continue; }
    const pm = line.match(/^(?:\+\+\+ b|--- a)\/(.+)$/);
    if (pm) paths.add(pm[1]);
  }
  return paths;
}

/**
 * Lint a spool workdir. Every check that applies pushes a result
 * { level: 'ok'|'warn'|'error', check, msg, where } (where = workdir-relative,
 * file:context-ish). Returns { results, errors, warnings }.
 */
export async function lintSpool(workdir) {
  const dir = path.resolve(workdir);
  const results = [];
  const push = (level, check, msg, where) => results.push({ level, check, msg, where });
  const ok = (check, msg, where) => push('ok', check, msg, where);
  const warn = (check, msg, where) => push('warn', check, msg, where);
  const error = (check, msg, where) => push('error', check, msg, where);

  // --- steps.mjs -------------------------------------------------------------
  let stepsMod = null;
  let generatedSteps = false;
  const sfPath = path.join(dir, 'steps.mjs');
  if (existsSync(sfPath)) {
    generatedSteps = readFileSync(sfPath, 'utf8').includes('generated by spool live');
    try {
      const mod = await import(pathToFileURL(sfPath).href + `?lint=${Date.now()}`);
      validateStepsModule(mod, 'steps.mjs');
      stepsMod = mod;
      ok('steps', `compiles and validates (${mod.steps.length} step${mod.steps.length === 1 ? '' : 's'})`, 'steps.mjs');
    } catch (e) {
      error('steps', e.message, 'steps.mjs');
    }
    if (stepsMod) {
      const seen = new Map();
      let clean = true;
      stepsMod.steps.forEach((s, i) => {
        if (typeof s.name !== 'string' || !s.name.trim()) {
          error('steps', `steps[${i}] has an empty name`, `steps.mjs:steps[${i}]`);
          clean = false;
          return;
        }
        if (seen.has(s.name)) {
          error('steps', `duplicate step name "${s.name}" (steps[${seen.get(s.name)}] and steps[${i}])`, `steps.mjs:steps[${i}]`);
          clean = false;
        } else {
          seen.set(s.name, i);
        }
      });
      if (clean) ok('steps', 'step names unique and non-empty', 'steps.mjs');
    }
  }

  // --- timeline.json ----------------------------------------------------------
  let timeline = null;
  const tlPath = path.join(dir, 'timeline.json');
  if (existsSync(tlPath)) {
    try {
      timeline = await readJsonSafe(tlPath);
    } catch (e) {
      error('timeline', `invalid JSON: ${e.message}`, 'timeline.json');
    }
    if (timeline) {
      let clean = true;
      if (timeline.version !== 1) {
        error('timeline', `version must be 1 (got ${JSON.stringify(timeline.version)})`, 'timeline.json');
        clean = false;
      }
      if (!Array.isArray(timeline.steps) || timeline.steps.length === 0) {
        error('timeline', 'steps must be a non-empty array', 'timeline.json');
        clean = false;
      } else {
        let prevEnd = 0;
        timeline.steps.forEach((s, i) => {
          const bad =
            typeof s.start !== 'number' || typeof s.end !== 'number' || s.end < s.start || s.start < prevEnd;
          if (bad) {
            error(
              'timeline',
              `steps[${i}] "${s.name ?? '?'}" start/end not monotonic (start=${s.start} end=${s.end} prev end=${prevEnd})`,
              `timeline.json:steps[${i}]`
            );
            clean = false;
          }
          if (typeof s.end === 'number') prevEnd = Math.max(prevEnd, s.end);
        });
      }
      if (clean) ok('timeline', `version 1, ${timeline.steps.length} steps, monotonic start/end`, 'timeline.json');
    }
  }

  // Recorded step names a tour stop can anchor to: timeline first, else a
  // steps.mjs generated by `spool live` (an authored script is not a recording).
  let recordedNames = null;
  let recordedSource = null;
  if (timeline && Array.isArray(timeline.steps)) {
    recordedNames = new Set(timeline.steps.map((s) => s.name).filter(Boolean));
    recordedSource = 'timeline.json';
  } else if (generatedSteps && stepsMod) {
    recordedNames = new Set(stepsMod.steps.map((s) => s.name).filter(Boolean));
    recordedSource = 'steps.mjs (generated)';
  }

  // --- em dashes in narration (authored content, not code) --------------------
  const narrations = [];
  if (stepsMod) stepsMod.steps.forEach((s, i) => narrations.push({ text: s.narration, where: `steps.mjs:steps[${i}]` }));
  else if (timeline && Array.isArray(timeline.steps)) {
    timeline.steps.forEach((s, i) => narrations.push({ text: s.narration, where: `timeline.json:steps[${i}]` }));
  }
  for (const n of narrations) {
    if (typeof n.text === 'string' && n.text.includes(EM_DASH)) {
      warn('emdash', 'narration contains an em dash (contract: none in authored content)', n.where);
    }
  }

  // --- tour.json ---------------------------------------------------------------
  const tourPath = path.join(dir, 'tour.json');
  if (existsSync(tourPath)) {
    let tour = null;
    try {
      tour = await readJsonSafe(tourPath);
    } catch (e) {
      error('tour', `invalid JSON: ${e.message}`, 'tour.json');
    }
    if (tour) {
      let shapeClean = true;
      if (tour.version !== 1) {
        error('tour', `version must be 1 (got ${JSON.stringify(tour.version)})`, 'tour.json');
        shapeClean = false;
      }
      if (!TOUR_MODES.includes(tour.mode)) {
        error('tour', `mode must be "walkthrough", "explainer", or null (got ${JSON.stringify(tour.mode)})`, 'tour.json');
        shapeClean = false;
      }
      const stops = Array.isArray(tour.stops) ? tour.stops : null;
      if (!stops || stops.length === 0) {
        error('tour', 'stops must be a non-empty array', 'tour.json');
        shapeClean = false;
      } else {
        if (stops.length < 3) warn('tour', `only ${stops.length} stop(s); 4 to 8 reads best`, 'tour.json');
        if (stops.length > 10) warn('tour', `${stops.length} stops; 4 to 8 reads best`, 'tour.json');
        stops.forEach((stop, i) => {
          const where = `tour.json:stops[${i}]`;
          for (const field of ['id', 'heading', 'prose']) {
            if (typeof stop[field] !== 'string' || !stop[field].trim()) {
              error('tour', `stops[${i}] needs a non-empty string \`${field}\``, where);
              shapeClean = false;
            }
          }
          for (const field of ['heading', 'prose']) {
            if (typeof stop[field] === 'string' && stop[field].includes(EM_DASH)) {
              warn('emdash', `${field} contains an em dash (contract: none in authored content)`, where);
            }
          }
        });
        // The silent-degrade killer: an unmatched stop publishes with step:null and
        // the watch page quietly loses its seek anchor. Here it is a hard error.
        if (recordedNames) {
          const unmatched = stops.filter((s) => !recordedNames.has(s.step ?? s.id));
          if (unmatched.length) {
            const names = `recorded steps in ${recordedSource}: ${[...recordedNames].join(', ')}`;
            for (const stop of unmatched) {
              error(
                'tour',
                `stop "${stop.step ?? stop.id}" matches no recorded step name (would publish with step: null, no seek anchor); ${names}`,
                `tour.json:stops[${stops.indexOf(stop)}]`
              );
            }
          } else {
            ok('tour', `all ${stops.length} stops map to recorded steps (${recordedSource})`, 'tour.json');
          }
        } else {
          warn('tour', 'no timeline.json or generated steps.mjs to check stop ids against', 'tour.json');
        }
        // Stops pointing at files the diff never touches render with no diff pane.
        const diffPath = path.join(dir, 'diff.patch');
        if (existsSync(diffPath)) {
          const known = diffPaths(await readFile(diffPath, 'utf8'));
          let allKnown = true;
          stops.forEach((stop, i) => {
            for (const f of stop.files || []) {
              if (f && typeof f.path === 'string' && !known.has(f.path)) {
                warn('tour', `stops[${i}] file "${f.path}" never appears in diff.patch`, `tour.json:stops[${i}]`);
                allKnown = false;
              }
            }
          });
          if (allKnown) ok('tour', 'all stop file paths appear in diff.patch', 'tour.json');
        }
      }
      if (shapeClean) ok('tour', `v1 shape valid (${(tour.stops || []).length} stops, mode: ${tour.mode ?? 'null'})`, 'tour.json');
    }
  }

  // --- vo/manifest.json ---------------------------------------------------------
  const manPath = path.join(dir, 'vo', 'manifest.json');
  if (existsSync(manPath)) {
    try {
      const manifest = await readJsonSafe(manPath);
      const segs = Array.isArray(manifest.segments) ? manifest.segments.length : 0;
      if (timeline && Array.isArray(timeline.steps) && segs !== timeline.steps.length) {
        warn('vo', `${segs} vo segment(s) vs ${timeline.steps.length} timeline step(s)`, 'vo/manifest.json');
      } else {
        ok('vo', `${segs} segment(s)`, 'vo/manifest.json');
      }
    } catch (e) {
      error('vo', `invalid JSON: ${e.message}`, 'vo/manifest.json');
    }
  }

  if (results.length === 0) {
    warn('lint', 'nothing to check (no steps.mjs, timeline.json, tour.json, or vo/manifest.json)', path.basename(dir));
  }

  const errors = results.filter((r) => r.level === 'error').length;
  const warnings = results.filter((r) => r.level === 'warn').length;
  return { results, errors, warnings };
}

const MARK = { ok: '✓', warn: 'warn', error: '✗' };

export function printLint({ results, errors, warnings }) {
  for (const r of results) {
    console.log(`  ${MARK[r.level].padEnd(4)} [${r.check}] ${r.msg}  (${r.where})`);
  }
  console.log(`\nlint: ${results.length - errors - warnings} ok, ${warnings} warning(s), ${errors} error(s)`);
}
