// generated by spool live — edit + `spool build` to reproduce this take.
export const config = {
  url: "https://spoolkit.dev",
  viewport: { width: 1600, height: 900 },
  title: "Spool, demoed by Spool",
};

export const steps = [
  {
    name: "the-pitch",
    narration: "This is Spool. When an agent ships a feature, it records a real walkthrough in the browser, narrates it, and hands you one link. No human ever hits record.",
    zoom: "none",
    run: async (page, h) => {
      await h.move(800,320); await h.pause(2400)
    },
  },
  {
    name: "how-it-works",
    narration: "Under the hood it is record first. The agent drives the app once at natural speed, narration generates in parallel, and the renderer fits every step to the voice.",
    zoom: "none",
    run: async (page, h) => {
      await page.locator("#features").scrollIntoViewIfNeeded(); await h.pause(2600)
    },
  },
  {
    name: "a-published-spool",
    narration: "Here is a published spool. A real continuous recording on a designed canvas, with word-synced captions baked in.",
    zoom: "none",
    run: async (page, h) => {
      await page.goto("https://spoolkit.dev/l/pl9bl6eUjcOaaiaErm7aWg"); await page.waitForSelector("video",{timeout:8000}); await h.pause(2600)
    },
  },
  {
    name: "chapters",
    narration: "Chapters come free from the step structure. Click one and the player jumps straight to that moment.",
    zoom: "auto",
    run: async (page, h) => {
      const chip=page.locator(".chapters button, .chapters a").nth(2); await chip.scrollIntoViewIfNeeded(); const b=await chip.boundingBox(); await h.click({x:Math.round(b.x+b.width/2),y:Math.round(b.y+b.height/2)}); await h.pause(2000)
    },
  },
  {
    name: "transcript",
    narration: "The full transcript rides along, timestamped per step.",
    zoom: "none",
    run: async (page, h) => {
      await page.evaluate(()=>{const el=[...document.querySelectorAll("h2,h3,div,span")].find(e=>["Transcript","TRANSCRIPT"].includes(e.textContent.trim())); if(el) el.scrollIntoView({behavior:"smooth",block:"start"}); else window.scrollBy({top:500,behavior:"smooth"});}); await h.pause(2200)
    },
  },
  {
    name: "receipts-for-agents",
    narration: "It is not just for humans. Every spool ships machine-readable receipts, so another agent can review the demo, verify what changed, and file bugs without watching a single frame.",
    zoom: "auto",
    run: async (page, h) => {
      const s=page.locator("summary").first(); await s.scrollIntoViewIfNeeded(); const b=await s.boundingBox(); await h.click({x:Math.round(b.x+80),y:Math.round(b.y+b.height/2)}); await h.pause(2400)
    },
  },
  {
    name: "edited-from-the-web",
    narration: "One more thing. The video on this page was edited after publishing. We re-voiced the intro and cut a step from the site itself, and the cloud pipeline re-rendered it in three minutes. That is Spool today.",
    zoom: "none",
    run: async (page, h) => {
      await page.evaluate(()=>window.scrollTo({top:0,behavior:"smooth"})); await h.pause(3400)
    },
  },
];
