// OS-level live capture adapter: full-display macOS screen capture via ffmpeg
// avfoundation, driven through the same HTTP control server as browser live mode.
// The agent drives the desktop out-of-band (osascript/cliclick/its own tools)
// between /step calls; /sh logs terminal-visible commands. Emits the same session
// contract (timeline.json + keyframes) with target:"os", plus a steps.os.md record.

import { createServer } from 'node:http';
import { spawn, execFile } from 'node:child_process';
import { promisify } from 'node:util';
import { mkdir, writeFile, rm } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { h264Encoder } from '../render/normalize.mjs';

const exec = promisify(execFile);
const FFMPEG = process.env.FFMPEG || 'ffmpeg';
const SETTLE_MS = 1500; // after capture is confirmed rolling, let t=0 settle before step 0
const STEP_SETTLE_MS = 250; // per-step end-state settle (same as browser modes)
const IDLE_TIMEOUT_MS = 5 * 60 * 1000;
const MAX_EDGE = 2560; // downscale cap on the long edge to keep render sane
const SH_TIMEOUT_MS = 120000;

const errln = (s) => process.stderr.write(s + '\n');
const trunc = (s, n) => { const t = String(s ?? ''); return t.length > n ? t.slice(0, n) : t; };

// Even-dimension downscale of the input so the long edge is ≤ MAX_EDGE (no upscaling).
function scaledDims(w, h) {
  const long = Math.max(w, h);
  if (long <= MAX_EDGE) return { w, h };
  const s = MAX_EDGE / long;
  const ev = (n) => Math.max(2, Math.round((n * s) / 2) * 2);
  return { w: ev(w), h: ev(h) };
}

// First "[N] Capture screen …" avfoundation device (the list call always exits non-zero).
async function detectScreenDevice(display) {
  const stderr = await exec(FFMPEG, ['-f', 'avfoundation', '-list_devices', 'true', '-i', ''])
    .then((r) => r.stderr, (e) => e.stderr || '');
  if (display != null) {
    const re = new RegExp(`\\[(\\d+)\\]\\s+Capture screen ${display}\\b`);
    const m = stderr.match(re);
    if (!m) throw new Error(`spool live --target os: no "Capture screen ${display}" avfoundation device`);
    return m[1];
  }
  const m = stderr.match(/\[(\d+)\]\s+Capture screen/);
  if (!m) throw new Error('spool live --target os: no "Capture screen" avfoundation device found');
  return m[1];
}

// Preflight: a short throwaway capture whose mean luma proves Screen Recording is
// granted. A TCC-denied avfoundation capture yields black frames, not an error.
async function assertScreenPermission(idx) {
  const tmp = path.join(tmpdir(), `spool-tcc-${process.pid}.mp4`);
  const tccMsg = 'spool live --target os: screen capture is black — grant Screen Recording to your terminal in '
    + 'System Settings → Privacy & Security → Screen Recording, then restart the terminal.';
  try {
    await exec(FFMPEG, ['-y', '-f', 'avfoundation', '-capture_cursor', '1', '-framerate', '30',
      '-i', `${idx}:none`, '-t', '1.2', '-c:v', 'libx264', '-preset', 'ultrafast', '-pix_fmt', 'yuv420p', tmp],
      { timeout: 20000 });
  } catch (e) {
    throw new Error(`${tccMsg}\n  (ffmpeg: ${trunc(e.stderr || e.message, 300)})`);
  }
  const stderr = await exec(FFMPEG, ['-i', tmp, '-vf', 'signalstats,metadata=print:key=lavfi.signalstats.YAVG', '-f', 'null', '-'])
    .then((r) => r.stderr, (e) => e.stderr || '');
  await rm(tmp, { force: true }).catch(() => {});
  const vals = [...stderr.matchAll(/YAVG=([\d.]+)/g)].map((m) => parseFloat(m[1]));
  const avg = vals.length ? vals.reduce((a, b) => a + b, 0) / vals.length : 0;
  if (avg < 8) throw new Error(tccMsg);
  return avg;
}

function readBody(req) {
  return new Promise((resolve, reject) => {
    let data = '';
    req.on('data', (c) => (data += c));
    req.on('end', () => resolve(data));
    req.on('error', reject);
  });
}

// bash -lc runner that never rejects — returns {code, stdout, stderr} for /sh.
function sh(cmd) {
  return new Promise((resolve) => {
    const p = spawn('bash', ['-lc', cmd], { timeout: SH_TIMEOUT_MS });
    let out = '', err = '';
    p.stdout.on('data', (d) => (out += d));
    p.stderr.on('data', (d) => (err += d));
    p.on('error', (e) => resolve({ code: -1, stdout: '', stderr: String(e) }));
    p.on('close', (code) => resolve({ code: code ?? -1, stdout: out, stderr: err }));
  });
}

function serializeStepsMd(config, steps) {
  const lines = [`# ${config.title || 'OS capture session'}`, '', '_generated by `spool live --target os`_', ''];
  for (const s of steps) {
    lines.push(`## Step ${s.i}: ${s.name}`, '', s.narration || '_(no narration)_', '');
    if (s.sh && s.sh.length) {
      for (const c of s.sh) lines.push(`- \`$ ${c.cmd}\` (exit ${c.exitCode})`);
      lines.push('');
    }
  }
  return lines.join('\n');
}

/**
 * Boot an OS-level live capture session and serve its control API on 127.0.0.1.
 * Resolves when finalized (via /end or the idle timeout). Same protocol as browser
 * live mode plus POST /sh; zoom defaults to "none" (no page driver → no auto-zoom).
 */
export async function liveOsSession({ workdir, title, display, window }) {
  const dir = path.resolve(workdir);
  await mkdir(dir, { recursive: true });

  if (window) errln('[live-os] --window capture is not implemented; falling back to full-display capture.');

  const idx = await detectScreenDevice(display);
  const luma = await assertScreenPermission(idx);
  errln(`[live-os] screen device ${idx} authorized (luma ${luma.toFixed(0)})`);

  const enc = await h264Encoder();
  const capPath = path.join(dir, 'capture.mp4');
  const scale = `scale=w='if(gte(iw,ih),min(${MAX_EDGE},iw),-2)':h='if(gte(iw,ih),-2,min(${MAX_EDGE},ih))'`;
  const args = ['-y', '-f', 'avfoundation', '-capture_cursor', '1', '-framerate', '30', '-i', `${idx}:none`,
    '-vf', `${scale},format=yuv420p`, '-r', '30', '-fps_mode', 'cfr', '-c:v', enc.name, ...enc.args,
    '-movflags', '+faststart', capPath];
  const ff = spawn(FFMPEG, args);
  let ffErr = '';
  ff.stderr.on('data', (d) => (ffErr += d));
  ff.on('error', (e) => (ffErr += `\nspawn error: ${e.message}`));

  // t=0 alignment: wait until the file is growing, then anchor the clock there and
  // settle. This lands within a few hundred ms of the capture's first frame; the
  // renderer's freeze-hold retiming forgives that slack.
  const { statSync } = await import('node:fs');
  const grew = async () => {
    let last = -1;
    for (let i = 0; i < 100; i++) {
      if (ff.exitCode != null) throw new Error(`spool live --target os: ffmpeg exited early: ${trunc(ffErr, 400)}`);
      const size = existsSync(capPath) ? statSync(capPath).size : 0;
      if (size > 0 && size > last) return;
      last = size;
      await new Promise((r) => setTimeout(r, 100));
    }
    throw new Error('spool live --target os: capture file never started growing');
  };
  await grew();
  const tOrigin = Date.now();
  const now = () => (Date.now() - tOrigin) / 1000;
  await new Promise((r) => setTimeout(r, SETTLE_MS));

  // Input dims from ffmpeg's own stream banner → output dims after the downscale.
  const dimMatch = ffErr.match(/Stream #0:0.*Video:.*?[,\s](\d{3,5})x(\d{3,5})/);
  const inW = dimMatch ? +dimMatch[1] : 0;
  const inH = dimMatch ? +dimMatch[2] : 0;
  const out = inW && inH ? scaledDims(inW, inH) : { w: 1920, h: 1080 };
  const viewport = { width: out.w, height: out.h };

  const config = { viewport };
  if (title) config.title = title;

  let current = null; // { name, narration, zoom, start, sh:[] }
  const steps = [];
  const telemetry = []; // console.jsonl analog (kind:"sh")

  const timeline = {
    version: 1,
    ...(title ? { title } : {}),
    target: 'os',
    viewport,
    capture: { device: `${idx}:none`, input: { width: inW, height: inH }, fps: 30 },
    fps: null,
    video: 'capture.mp4',
    steps: [],
    total: 0,
  };

  // --- session state machine ------------------------------------------------
  async function keyframe(i) {
    const nn = String(i).padStart(2, '0');
    await mkdir(path.join(dir, 'keyframes'), { recursive: true });
    await exec('screencapture', ['-x', '-t', 'png', path.join(dir, 'keyframes', `step_${nn}.png`)]).catch(() => {});
  }

  async function closeStep() {
    if (!current) return;
    await new Promise((r) => setTimeout(r, STEP_SETTLE_MS)); // capture the settled end state
    const i = steps.length;
    await keyframe(i);
    steps.push({
      i, name: current.name, narration: current.narration, zoom: current.zoom,
      start: current.start, end: +now().toFixed(3),
      clicks: current.zoom && typeof current.zoom === 'object' ? [{ x: current.zoom.x, y: current.zoom.y, t: current.start }] : [],
      sh: current.sh,
    });
    current = null;
  }

  function doStep(p) {
    if (typeof p.name !== 'string' || !p.name.trim()) return { status: 400, body: { ok: false, error: 'name is required' } };
    if (typeof p.narration !== 'string' || !p.narration.trim()) {
      return { status: 400, body: { ok: false, error: 'narration is required (the renderer fits each step window to it)' } };
    }
    let zoom = 'none';
    if (p.zoom && typeof p.zoom === 'object' && p.zoom.x != null && p.zoom.y != null) zoom = { x: p.zoom.x, y: p.zoom.y, ...(p.zoom.scale ? { scale: p.zoom.scale } : {}) };
    return closeStep().then(() => {
      current = { name: p.name.trim(), narration: p.narration.trim(), zoom, start: +now().toFixed(3), sh: [] };
      return { status: 200, body: { ok: true, index: steps.length, name: current.name } };
    });
  }

  async function doSh(p) {
    if (typeof p.cmd !== 'string' || !p.cmd.trim()) return { status: 400, body: { ok: false, error: 'cmd is required' } };
    const r = await sh(p.cmd);
    const head = trunc(r.stdout || r.stderr, 500).replace(/\n+$/, '');
    telemetry.push({ t: +now().toFixed(3), kind: 'sh', cmd: p.cmd, exitCode: r.code, stdoutHead: head });
    if (current) current.sh.push({ cmd: p.cmd, exitCode: r.code });
    return { status: 200, body: { ok: r.code === 0, exitCode: r.code, stdout: trunc(r.stdout, 4096) } };
  }

  function status() {
    return {
      ok: true, target: 'os', elapsed: +now().toFixed(2), completed: steps.length,
      current: current ? { index: steps.length, name: current.name } : null,
    };
  }

  async function stopCapture() {
    if (ff.exitCode != null) return;
    const closed = new Promise((r) => ff.once('close', r));
    ff.kill('SIGINT'); // clean stop lets ffmpeg finalize the moov atom
    const killed = new Promise((r) => setTimeout(() => { ff.kill('SIGKILL'); r(); }, 8000));
    await Promise.race([closed, killed]);
    await closed.catch(() => {});
  }

  let finalized = false;
  let finalizeSummary = null;
  async function finalize() {
    if (finalized) return finalizeSummary;
    finalized = true;
    await closeStep();
    timeline.total = +now().toFixed(3);
    await stopCapture();
    timeline.steps = steps.map((s) => ({ i: s.i, name: s.name, start: s.start, end: s.end, zoom: s.zoom, clicks: s.clicks, narration: s.narration }));
    await writeFile(path.join(dir, 'console.jsonl'), telemetry.map((e) => JSON.stringify(e)).join('\n') + (telemetry.length ? '\n' : ''));
    await writeFile(path.join(dir, 'timeline.json'), JSON.stringify(timeline, null, 2) + '\n');
    await writeFile(path.join(dir, 'steps.os.md'), serializeStepsMd(config, steps) + '\n');
    finalizeSummary = { dir, steps: steps.length, total: timeline.total };
    return finalizeSummary;
  }

  async function discardTake() {
    finalized = true;
    await stopCapture();
    await rm(capPath, { force: true }).catch(() => {});
  }

  // --- serialize control ops so overlapping requests can't interleave -------
  let lock = Promise.resolve();
  function serialize(fn) {
    const run = lock.then(fn, fn);
    lock = run.then(() => {}, () => {});
    return run;
  }

  let shuttingDown = false;
  async function shutdown() {
    if (shuttingDown) return;
    shuttingDown = true;
    clearTimeout(idleTimer);
    server.close();
    await stopCapture().catch(() => {});
    resolveDone();
  }

  let idleTimer;
  function resetIdle() {
    clearTimeout(idleTimer);
    idleTimer = setTimeout(async () => {
      errln('[live-os] idle 5m — finalizing session');
      await serialize(() => (finalized ? null : finalize()));
      await shutdown();
    }, IDLE_TIMEOUT_MS);
  }

  function sendJson(res, statusCode, body, cb) {
    res.writeHead(statusCode, { 'Content-Type': 'application/json' });
    res.end(JSON.stringify(body), cb);
  }

  const server = createServer((req, res) => {
    resetIdle();
    handle(req, res).catch((err) => sendJson(res, 500, { ok: false, error: err.message }));
  });

  async function handle(req, res) {
    const u = new URL(req.url, 'http://127.0.0.1');
    if (req.method === 'GET' && u.pathname === '/status') return sendJson(res, 200, status());
    const raw = await readBody(req);
    let payload = {};
    if (raw) {
      try { payload = JSON.parse(raw); } catch { return sendJson(res, 400, { ok: false, error: 'invalid JSON body' }); }
    }
    if (req.method === 'POST' && u.pathname === '/step') {
      const r = await serialize(() => doStep(payload));
      return sendJson(res, r.status, r.body);
    }
    if (req.method === 'POST' && u.pathname === '/sh') {
      const r = await serialize(() => doSh(payload));
      return sendJson(res, r.status, r.body);
    }
    if (req.method === 'POST' && u.pathname === '/end') {
      const r = await serialize(async () => {
        if (payload.discard) { await discardTake(); return { ok: true, discarded: true }; }
        return { ok: true, ...(await finalize()) };
      });
      return sendJson(res, 200, r, () => shutdown());
    }
    return sendJson(res, 404, { ok: false, error: `no route ${req.method} ${u.pathname}` });
  }

  let resolveDone;
  const done = new Promise((r) => (resolveDone = r));
  await new Promise((r) => server.listen(0, '127.0.0.1', r));
  const port = server.address().port;
  resetIdle();
  process.stdout.write(JSON.stringify({ port, session: dir }) + '\n');
  errln(`[live-os] capturing ${viewport.width}x${viewport.height} — control on 127.0.0.1:${port}`);
  errln(`  step: curl -sX POST 127.0.0.1:${port}/step -d '{"name":"open","narration":"..."}'`);
  errln(`  sh:   curl -sX POST 127.0.0.1:${port}/sh   -d '{"cmd":"open -a Finder ."}'`);
  errln(`  end:  curl -sX POST 127.0.0.1:${port}/end`);
  return done;
}
