// Live authoring mode: boot the same recording context as `spool record` but drive
// it through an HTTP control server instead of a steps.mjs script. The agent drives
// the app ONCE (curl per step) and the session is emitted as the same video.webm +
// timeline.json contract, plus a generated steps.mjs snapshot so the take is
// reproducible/editable as a scripted spool later.

import { chromium } from 'playwright';
import { createServer } from 'node:http';
import { execFile } from 'node:child_process';
import { promisify } from 'node:util';
import { mkdir, rename, writeFile, readFile, rm } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import path from 'node:path';
import { pathToFileURL } from 'node:url';
import { CURSOR_INIT_SCRIPT, makeHelpers } from './cursor.js';

const exec = promisify(execFile);
const FFMPEG = process.env.FFMPEG || 'ffmpeg';
const FFPROBE = process.env.FFPROBE || 'ffprobe';
const SETTLE_MS = 1000; // after goto, let first paint/layout settle
const STEP_SETTLE_MS = 250; // per-step end-state settle (same as the scripted harness)
const IDLE_TIMEOUT_MS = 5 * 60 * 1000; // finalize a forgotten session instead of leaking a browser
const AsyncFunction = Object.getPrototypeOf(async () => {}).constructor;

const errln = (s) => process.stderr.write(s + '\n');
const indent = (code, n) =>
  code.replace(/^\n+/, '').replace(/\s+$/, '').split('\n').map((l) => (l.length ? ' '.repeat(n) + l : '')).join('\n');

function serializeConfig(config, prep) {
  const vp = config.viewport || { width: 1600, height: 900 };
  const lines = ['export const config = {', `  url: ${JSON.stringify(config.url)},`,
    `  viewport: { width: ${vp.width}, height: ${vp.height} },`];
  if (config.title) lines.push(`  title: ${JSON.stringify(config.title)},`);
  if (prep && prep.length) {
    lines.push('  prep: async (page, h) => {', prep.map((c) => indent(c, 4)).join('\n'), '  },');
  }
  lines.push('};');
  return lines.join('\n');
}

function serializeSteps(steps) {
  const body = steps.map((s) => {
    const run = s.snippets && s.snippets.length
      ? s.snippets.map((c) => indent(c, 6)).join('\n')
      : '      // no recorded actions';
    return ['  {', `    name: ${JSON.stringify(s.name)},`, `    narration: ${JSON.stringify(s.narration || '')},`,
      `    zoom: ${JSON.stringify(s.zoom ?? 'auto')},`, '    run: async (page, h) => {', run, '    },', '  },'].join('\n');
  }).join('\n');
  return `export const steps = [\n${body}\n];`;
}

// Emit the reproducible steps.mjs snapshot. prep = pre-step-0 snippets (login/prep).
export async function writeGeneratedSteps({ dir, config, steps, prep }) {
  const src = `// generated by spool live — edit + \`spool build\` to reproduce this take.\n`
    + `${serializeConfig(config, prep)}\n\n${serializeSteps(steps)}\n`;
  await writeFile(path.join(dir, 'steps.mjs'), src);
}

// One keyframe per step, pulled from video.webm (post-first-click or step midpoint),
// so a consuming agent can eyeball the take before running `spool finish`.
async function writeKeyframes(dir, steps) {
  const kfDir = path.join(dir, 'keyframes');
  await mkdir(kfDir, { recursive: true });
  const video = path.join(dir, 'video.webm');
  let dur = Infinity;
  try {
    const { stdout } = await exec(FFPROBE, ['-v', 'error', '-show_entries', 'format=duration', '-of', 'default=nk=1:nw=1', video]);
    dur = parseFloat(stdout.trim()) || Infinity;
  } catch { /* leave unclamped */ }
  for (const s of steps) {
    const clicks = s.clicks || [];
    let t = clicks.length ? clicks[0].t + 0.3 : (s.start + s.end) / 2;
    t = Math.min(Math.max(t, 0), Math.max(0, dur - 0.05));
    const nn = String(s.i).padStart(2, '0');
    await exec(FFMPEG, ['-y', '-ss', String(t), '-i', video, '-frames:v', '1', '-update', '1',
      '-vf', 'scale=1280:-2', path.join(kfDir, `step_${nn}.png`)]).catch(() => {});
  }
}

// Up to 10 visible clickable/input elements as { selector, text } so a failed
// locator comes back with what WAS on the page. Runs in the page; best-effort.
function collectCandidates(page) {
  return page.evaluate(() => {
    const out = [];
    const els = document.querySelectorAll('a, button, input, select, textarea, [role="button"], [onclick]');
    for (const el of els) {
      if (out.length >= 10) break;
      const r = el.getBoundingClientRect();
      if (!r.width || !r.height) continue;
      const st = getComputedStyle(el);
      if (st.visibility === 'hidden' || st.display === 'none') continue;
      let sel = el.tagName.toLowerCase();
      if (el.id) sel += `#${el.id}`;
      else if (el.getAttribute('aria-label')) sel += `[aria-label="${el.getAttribute('aria-label')}"]`;
      else if (typeof el.className === 'string' && el.className.trim()) {
        sel += `.${el.className.trim().split(/\s+/).slice(0, 2).join('.')}`;
      }
      const text = (el.innerText || el.value || el.placeholder || '').trim().slice(0, 40);
      out.push({ selector: sel, text });
    }
    return out;
  });
}

const LOCATORISH = /timeout|timed out|waiting for|locator|selector|strict mode|not visible|not attached|no element/i;

// The raw material for debug/session-notes.md: what an agent folds into project
// knowledge `set_recording` ops after the session.
function sessionNotes(failures) {
  const lines = ['# spool live session notes: raw /js failure forensics to fold into project knowledge `set_recording` ops.', ''];
  failures.forEach((f, i) => {
    lines.push(`## failure ${i + 1}`, '', '```js', f.code, '```', '', `error: ${f.error}`);
    if (f.screenshot) lines.push(`screenshot: ${f.screenshot}`);
    lines.push('');
  });
  return lines.join('\n');
}

function readBody(req) {
  return new Promise((resolve, reject) => {
    let data = '';
    req.on('data', (c) => (data += c));
    req.on('end', () => resolve(data));
    req.on('error', reject);
  });
}

/**
 * Boot a live recording session and serve its control API on 127.0.0.1:<ephemeral>.
 * Resolves when the session is finalized (via /end or the idle timeout).
 */
export async function liveSession({ workdir, url, title, headed = false }) {
  const dir = path.resolve(workdir);
  await mkdir(dir, { recursive: true });

  // URL/viewport/title come from --url/--title, falling back to an existing steps.mjs config.
  let cfg = {};
  const sf = path.join(dir, 'steps.mjs');
  if (existsSync(sf)) {
    try { cfg = (await import(pathToFileURL(sf).href + `?t=${Date.now()}`)).config || {}; } catch { /* ignore */ }
  }
  const resolvedUrl = url || cfg.url;
  if (!resolvedUrl) throw new Error('spool live: no URL (pass --url or provide a steps.mjs with config.url)');
  const config = { url: resolvedUrl, viewport: cfg.viewport || { width: 1600, height: 900 } };
  if (title || cfg.title) config.title = title || cfg.title;
  const viewport = config.viewport;

  const browser = await chromium.launch({ headless: !headed });
  const context = await browser.newContext({ viewport, recordVideo: { dir, size: viewport } });
  await context.addInitScript(CURSOR_INIT_SCRIPT);
  const page = await context.newPage();
  // Fast-fail selectors: a fumbled /js snippet must not record 30s of dead air into the take.
  page.setDefaultTimeout(5000);
  const tOrigin = Date.now(); // video t=0
  const now = () => (Date.now() - tOrigin) / 1000;
  const video = page.video();

  const state = { x: Math.round(viewport.width / 2), y: Math.round(viewport.height / 2) };
  let current = null; // { name, narration, zoom, start, clicks:[], snippets:[] }
  const prep = []; // snippets executed before the first /step → config.prep
  const steps = [];
  const logClick = (x, y) => {
    if (current) current.clicks.push({ x: Math.round(x), y: Math.round(y), t: +now().toFixed(3) });
  };
  const h = makeHelpers(page, state, logClick);

  const telemetry = [];
  const trunc = (s) => (typeof s === 'string' && s.length > 2000 ? s.slice(0, 2000) : String(s ?? ''));
  const logEvent = (e) => telemetry.push({ t: +now().toFixed(3), ...e, text: trunc(e.text) });
  page.on('console', (m) => logEvent({ kind: 'console', level: m.type(), text: m.text() }));
  page.on('pageerror', (err) => logEvent({ kind: 'pageerror', text: err && err.message ? err.message : String(err) }));
  page.on('requestfailed', (req) => {
    const f = req.failure();
    logEvent({ kind: 'requestfailed', text: `${req.method()} ${req.url()} ${f ? f.errorText : ''}`.trim() });
  });

  const timeline = {
    version: 1,
    ...(config.title ? { title: config.title } : {}),
    url: config.url,
    viewport,
    fps: null,
    video: 'video.webm',
    steps: [],
    total: 0,
  };

  try {
    await page.goto(config.url, { waitUntil: 'load' });
    await page.waitForTimeout(SETTLE_MS);
  } catch (err) {
    await browser.close().catch(() => {});
    throw new Error(`spool live: initial goto failed: ${err.message}`);
  }

  // --- session state machine ------------------------------------------------
  async function closeStep() {
    if (!current) return;
    await page.waitForTimeout(STEP_SETTLE_MS); // capture the settled end state
    steps.push({
      i: steps.length,
      name: current.name,
      narration: current.narration,
      zoom: current.zoom,
      start: current.start,
      end: +now().toFixed(3),
      clicks: current.clicks,
      snippets: current.snippets,
    });
    current = null;
  }

  async function doStep(p) {
    if (typeof p.name !== 'string' || !p.name.trim()) return { status: 400, body: { ok: false, error: 'name is required' } };
    if (typeof p.narration !== 'string' || !p.narration.trim()) {
      return { status: 400, body: { ok: false, error: 'narration is required (the renderer fits each step window to it)' } };
    }
    await closeStep();
    current = { name: p.name.trim(), narration: p.narration.trim(), zoom: p.zoom ?? 'auto', start: +now().toFixed(3), clicks: [], snippets: [] };
    return { status: 200, body: { ok: true, index: steps.length, name: current.name, url: page.url() } };
  }

  // Failure forensics: screenshot + recent telemetry (+ candidates on locator-ish
  // errors), and a failures[] entry for session-notes.md. Must never throw.
  let jsFails = 0;
  const failures = [];
  async function jsFailureInfo(errMsg, code) {
    const info = { console: telemetry.slice(-8) };
    const n = ++jsFails;
    try {
      const dbg = path.join(dir, 'debug');
      await mkdir(dbg, { recursive: true });
      const shot = path.join(dbg, `jsfail_${n}.png`);
      await page.screenshot({ path: shot });
      info.screenshot = shot;
    } catch { /* screenshot is best-effort */ }
    if (LOCATORISH.test(errMsg)) {
      try { info.candidates = await collectCandidates(page); } catch { /* best-effort */ }
    }
    failures.push({
      code: code.replace(/^\n+/, '').split('\n').slice(0, 3).join('\n'),
      error: errMsg,
      screenshot: info.screenshot ?? null,
    });
    return info;
  }

  async function doJs(p) {
    if (typeof p.code !== 'string' || !p.code.trim()) return { status: 400, body: { ok: false, error: 'code is required' } };
    let fn;
    try { fn = new AsyncFunction('page', 'h', p.code); } catch (e) {
      const error = `compile: ${e.message}`;
      return { status: 200, body: { ok: false, error, url: page.url(), ...(await jsFailureInfo(error, p.code)) } };
    }
    try {
      const result = await fn(page, h);
      (current ? current.snippets : prep).push(p.code); // only successful snippets snapshot
      let out;
      try { out = result === undefined ? undefined : JSON.parse(JSON.stringify(result)); } catch { out = String(result); }
      const body = { ok: true, url: page.url() };
      if (out !== undefined) body.result = out;
      return { status: 200, body };
    } catch (e) {
      return { status: 200, body: { ok: false, error: e.message, url: page.url(), ...(await jsFailureInfo(e.message, p.code)) } };
    }
  }

  function status() {
    return {
      ok: true, url: page.url(), elapsed: +now().toFixed(2), completed: steps.length,
      current: current ? { index: steps.length, name: current.name } : null,
    };
  }

  let finalized = false;
  let finalizeSummary = null;
  async function finalize() {
    if (finalized) return finalizeSummary;
    finalized = true;
    await closeStep();
    timeline.total = +now().toFixed(3);
    timeline.steps = steps.map((s) => ({
      i: s.i, name: s.name, start: s.start, end: s.end, zoom: s.zoom, clicks: s.clicks, narration: s.narration,
    }));
    await context.close(); // finalizes video.webm
    await writeFile(path.join(dir, 'console.jsonl'), telemetry.map((e) => JSON.stringify(e)).join('\n') + (telemetry.length ? '\n' : ''));
    const src = await video.path();
    await rename(src, path.join(dir, 'video.webm'));
    await writeFile(path.join(dir, 'timeline.json'), JSON.stringify(timeline, null, 2) + '\n');
    await writeGeneratedSteps({ dir, config, steps, prep });
    await writeKeyframes(dir, steps).catch(() => {});
    if (failures.length) {
      await mkdir(path.join(dir, 'debug'), { recursive: true }).catch(() => {});
      await writeFile(path.join(dir, 'debug', 'session-notes.md'), sessionNotes(failures)).catch(() => {});
    }
    finalizeSummary = { dir, steps: steps.length, total: timeline.total };
    return finalizeSummary;
  }

  async function discardTake() {
    finalized = true;
    await context.close().catch(() => {});
    try { await rm(await video.path()); } catch { /* nothing to remove */ }
  }

  // --- serialize page ops so overlapping requests can't interleave ----------
  let lock = Promise.resolve();
  function serialize(fn) {
    const run = lock.then(fn, fn);
    lock = run.then(() => {}, () => {});
    return run;
  }

  let shuttingDown = false;
  async function shutdown() {
    if (shuttingDown) return;
    shuttingDown = true;
    clearTimeout(idleTimer);
    server.close();
    await browser.close().catch(() => {});
    resolveDone();
  }

  let idleTimer;
  function resetIdle() {
    clearTimeout(idleTimer);
    idleTimer = setTimeout(async () => {
      errln('[live] idle 5m — finalizing session');
      await serialize(() => (finalized ? null : finalize()));
      await shutdown();
    }, IDLE_TIMEOUT_MS);
  }

  function sendJson(res, statusCode, body, cb) {
    res.writeHead(statusCode, { 'Content-Type': 'application/json' });
    res.end(JSON.stringify(body), cb);
  }

  const server = createServer((req, res) => {
    resetIdle();
    handle(req, res).catch((err) => sendJson(res, 500, { ok: false, error: err.message }));
  });

  async function handle(req, res) {
    const u = new URL(req.url, 'http://127.0.0.1');
    if (req.method === 'GET' && u.pathname === '/status') return sendJson(res, 200, status());
    const raw = await readBody(req);
    let payload = {};
    if (raw) {
      try { payload = JSON.parse(raw); } catch { return sendJson(res, 400, { ok: false, error: 'invalid JSON body' }); }
    }
    if (req.method === 'POST' && u.pathname === '/step') {
      const r = await serialize(() => doStep(payload));
      return sendJson(res, r.status, r.body);
    }
    if (req.method === 'POST' && u.pathname === '/js') {
      const r = await serialize(() => doJs(payload));
      return sendJson(res, r.status, r.body);
    }
    if (req.method === 'POST' && u.pathname === '/end') {
      const r = await serialize(async () => {
        if (payload.discard) { await discardTake(); return { ok: true, discarded: true }; }
        return { ok: true, ...(await finalize()) };
      });
      return sendJson(res, 200, r, () => shutdown());
    }
    return sendJson(res, 404, { ok: false, error: `no route ${req.method} ${u.pathname}` });
  }

  let resolveDone;
  const done = new Promise((r) => (resolveDone = r));
  await new Promise((r) => server.listen(0, '127.0.0.1', r));
  const port = server.address().port;
  resetIdle();
  // The one machine-readable line on stdout; everything else goes to stderr.
  process.stdout.write(JSON.stringify({ port, session: dir }) + '\n');
  errln(`[live] recording ${config.url} — control on 127.0.0.1:${port}`);
  errln(`  step: curl -sX POST 127.0.0.1:${port}/step -d '{"name":"open","narration":"..."}'`);
  errln(`  js:   curl -sX POST 127.0.0.1:${port}/js   -d '{"code":"await h.click(\\"#id\\")"}'`);
  errln(`  end:  curl -sX POST 127.0.0.1:${port}/end`);
  return done;
}
