// Plan Spool narration + steps generator.
//
// Turns a validated packet (plan.json + evidence.json) into `plan.script.json`:
// an ordered narration outline, one visual source per chapter, and the decision
// card. From that one artifact both authoring paths are driven — a generated
// `steps.mjs` (scripted) and the `POST /step` bodies of a live session.
//
// Two rules shape everything here:
//
// 1. The generator never invents a claim. Author sentences are copied verbatim;
//    the generator only adds fixed lead-ins that carry no facts. Every chapter
//    records the packet paths it was built from (`sources`), and the linter
//    resolves each one, so an invented claim fails as a lint error rather than
//    reaching a reviewer.
// 2. It is deterministic. The same packet and style always produce the same
//    bytes, so a regenerated script diffs cleanly and a review is repeatable.
//
// See CONTRACTS.md "Plan Spools" → "plan.script.json".

import { readFile, writeFile } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import { join, resolve } from 'node:path';
import { readPrefs } from '../config/prefs.mjs';
import { CHAPTER_IDS } from './schema.mjs';

export const SCRIPT_FILE = 'plan.script.json';
export const SCRIPT_VERSION = 1;
export const STEPS_MARKER = 'generated by spool plan generate';

// Narration pace of the shipped VO register, measured on rendered spools:
// ~156 words per minute. Used for the duration estimate only; the renderer
// retimes each step to the real wav (see CONTRACTS.md "Render layer inputs").
export const WORDS_PER_SECOND = 2.6;
// Per-chapter settle the renderer holds after the narration ends.
const CHAPTER_SETTLE_SECONDS = 0.6;

export const DURATION_MIN_SECONDS = 45;
export const DURATION_MAX_SECONDS = 120;
export const CHAPTER_MIN = 3;
export const CHAPTER_MAX = 6;

// The acceptance shape: a plan a reviewer can act on always says what exists,
// how it will be built, what is uncertain, and what it needs from them.
export const REQUIRED_CHAPTERS = ['context', 'approach', 'risks', 'decision'];

const WORDS_PER_CHAPTER_MAX = 60;
const WORDS_PER_CHAPTER_MIN = 8;

const EM_DASH = '\u2014'; // kept as an escape (no literal em dashes in source)

// --- style: voice + visual language ----------------------------------------

// The reviewer-facing register. `instructions` is the TTS voice direction
// (`spool vo` reads it from plan.script.json when no explicit register is set),
// `lead` supplies the fixed, fact-free sentences the templates may add.
export const VOICE_PROFILES = {
  'direct-technical': {
    id: 'direct-technical',
    label: 'Direct and technical',
    description: 'An engineer briefing another engineer. Short sentences, named things, no warm-up.',
    instructions:
      'Affect: an engineer briefing a colleague on work they are about to start. ' +
      'Tone: direct, precise, and unhurried, with no salesmanship and no warm-up. ' +
      'Pronunciation: crisp and articulate; read file names, identifiers and numbers exactly as written. ' +
      'Pauses: a clear beat after each claim, so the listener can check it against the screen. ' +
      'Emotion: calm confidence. Never announcer-like, never breathy, never enthusiastic about the plan itself.',
    lead: {
      context: 'First, where things stand today.',
      outcome: 'Here is what changes.',
      approach: (n) => `The approach is ${numberWord(n)} step${n === 1 ? '' : 's'}.`,
      risks: 'Now the risks.',
      assumptions: 'This plan assumes the following.',
      alternatives: 'On alternatives.',
      tradeoffs: 'The tradeoffs.',
      decision: 'That is the plan.',
      onScreen: (label) => `On screen: ${label}.`,
      step: (i) => `Step ${numberWord(i)}.`,
      options: 'You can',
    },
  },
  'calm-client-ready': {
    id: 'calm-client-ready',
    label: 'Calm and client-ready',
    description: 'A lead walking a stakeholder through a proposal. Fuller sentences, no jargon framing.',
    instructions:
      'Affect: a calm project lead walking a client through a proposal before work starts. ' +
      'Tone: warm, measured, and reassuring, confident without pressure. ' +
      'Pronunciation: clear and steady, with light emphasis on outcomes and on what is being asked for. ' +
      'Pauses: generous, purposeful pauses between points, giving the listener room to think. ' +
      'Emotion: quiet reassurance. Never announcer-like, never salesy, never rushed.',
    lead: {
      context: "Let's start with where things are today.",
      outcome: 'Here is what will be different.',
      approach: (n) => `Here is how we get there, in ${numberWord(n)} step${n === 1 ? '' : 's'}.`,
      risks: 'A few things are worth knowing before you decide.',
      assumptions: 'We are taking the following as given.',
      alternatives: 'On other options.',
      tradeoffs: 'The tradeoffs there.',
      decision: 'That is the proposal.',
      onScreen: (label) => `You are looking at ${label}.`,
      step: (i) => `Step ${numberWord(i)}.`,
      options: 'You can',
    },
  },
};

// Which evidence a chapter prefers to show when the author gives no hint.
// Both languages fall back to whatever the chapter actually has.
export const VISUAL_LANGUAGES = {
  'code-forward': {
    id: 'code-forward',
    label: 'Code-forward',
    description: 'Show the source, the diff, and the test output. Names the artifact on screen.',
    prefer: ['file', 'commit', 'test', 'console', 'image', 'url'],
    nameArtifact: true,
  },
  'product-forward': {
    id: 'product-forward',
    label: 'Product-forward',
    description: 'Show the running product and the screens a user touches. Keeps file names out of the narration.',
    prefer: ['url', 'image', 'file', 'test', 'commit', 'console'],
    nameArtifact: false,
  },
};

// Approved direction: an engineer briefing an engineer, over the running
// product. File names stay on the screen, not in the narration.
export const DEFAULT_VOICE = 'direct-technical';
export const DEFAULT_VISUALS = 'product-forward';

/**
 * Resolve the generation style: explicit > env > ~/.spool.json > default.
 * Kept out of `spool setup`'s questionnaire on purpose: it is a per-project
 * editorial choice, not an installation preference.
 */
export async function resolveStyle({ voice, visuals } = {}) {
  const prefs = await readPrefs();
  const pick = (explicit, envKey, prefKey, fallback, table, label) => {
    const value = explicit || process.env[envKey] || prefs[prefKey] || fallback;
    if (!table[value]) {
      throw new Error(`unknown ${label} "${value}"; choose one of: ${Object.keys(table).join(', ')}`);
    }
    return table[value];
  };
  return {
    voice: pick(voice, 'SPOOL_PLAN_VOICE', 'planVoice', DEFAULT_VOICE, VOICE_PROFILES, 'plan voice'),
    visuals: pick(visuals, 'SPOOL_PLAN_VISUALS', 'planVisuals', DEFAULT_VISUALS, VISUAL_LANGUAGES, 'plan visual language'),
  };
}

// --- text helpers ------------------------------------------------------------

const NUMBER_WORDS = ['zero', 'one', 'two', 'three', 'four', 'five', 'six', 'seven', 'eight', 'nine', 'ten'];
function numberWord(n) {
  return NUMBER_WORDS[n] ?? String(n);
}

// Author text is copied verbatim; the only edit is a trailing period so two
// sentences do not run together when spoken.
function sentence(text) {
  const t = String(text).trim();
  if (!t) return '';
  return /[.!?]$/.test(t) ? t : `${t}.`;
}

const joinSentences = (parts) => parts.filter(Boolean).join(' ');

export const countWords = (text) => (String(text).trim() ? String(text).trim().split(/\s+/).length : 0);

const round1 = (x) => Math.round(x * 10) / 10;

/** Seconds one narration block is expected to take, including the settle. */
export function estimateSeconds(narration) {
  return round1(countWords(narration) / WORDS_PER_SECOND + CHAPTER_SETTLE_SECONDS);
}

// The reviewer-facing phrasing of the decision options, so the video asks for
// the same actions the decision card offers.
function optionPhrase(option, alternatives) {
  if (option === 'approve') return 'approve it';
  if (option === 'redirect') return 'redirect with changes';
  if (option === 'ask-question') return 'ask a question against any moment';
  if (option === 'needs-input') return 'mark it as needing input';
  const alt = option.startsWith('alternative:') ? alternatives.find((a) => a.id === option.slice('alternative:'.length)) : null;
  return alt ? `choose the alternative: ${alt.summary.replace(/[.]$/, '')}` : option;
}

function optionsSentence(lead, options, alternatives) {
  const phrases = options.map((o) => optionPhrase(o, alternatives));
  if (!phrases.length) return '';
  const list = phrases.length === 1 ? phrases[0] : `${phrases.slice(0, -1).join(', ')}, or ${phrases[phrases.length - 1]}`;
  return `${lead} ${list}.`;
}

export function optionLabel(option, alternatives) {
  if (option === 'approve') return 'Approve';
  if (option === 'redirect') return 'Redirect';
  if (option === 'ask-question') return 'Ask a question';
  if (option === 'needs-input') return 'Needs input';
  const alt = option.startsWith('alternative:') ? alternatives.find((a) => a.id === option.slice('alternative:'.length)) : null;
  return alt ? alt.summary.replace(/[.]$/, '') : option;
}

// --- visuals -----------------------------------------------------------------

// Evidence kind → how the chapter is shown. `card` is the static plan card the
// plan visual templates render (R2.2); until then it holds the current frame.
const VISUAL_KIND_BY_EVIDENCE = {
  file: 'code',
  commit: 'code',
  url: 'browser',
  image: 'image',
  test: 'terminal',
  console: 'terminal',
};

function evidenceById(evidence, id) {
  return (evidence?.items || []).find((it) => it.id === id) || null;
}

// Evidence a chapter may show: descriptors that name the chapter, plus the ones
// its own claims reference. Order follows the visual language's preference,
// then the declaration order in evidence.json, so the choice is deterministic.
function chapterEvidence(chapterId, { plan, evidence }, prefer) {
  const ids = [];
  const add = (id) => { if (id && !ids.includes(id)) ids.push(id); };
  for (const item of evidence?.items || []) {
    if ((item.chapterIds || []).includes(chapterId)) add(item.id);
  }
  const claimsFor = (list, defaultChapter) => {
    for (const entry of list || []) {
      if ((entry.chapterId || defaultChapter) !== chapterId) continue;
      for (const id of entry.evidence || []) add(id);
    }
  };
  claimsFor(plan.currentState, 'context');
  claimsFor(plan.approach, 'approach');
  const items = ids.map((id) => evidenceById(evidence, id)).filter(Boolean);
  return items.sort((a, b) => {
    const ra = prefer.indexOf(a.kind);
    const rb = prefer.indexOf(b.kind);
    return (ra < 0 ? prefer.length : ra) - (rb < 0 ? prefer.length : rb);
  });
}

// An author hint on the chapter always wins. `chapters[].visual` is additive to
// plan.json: the packet validator ignores it, this generator is what checks it.
function authoredVisual(chapter) {
  const v = chapter?.visual;
  if (!v || typeof v !== 'object' || Array.isArray(v)) return null;
  return v;
}

function resolveVisual(chapterId, chapter, packet, language) {
  const hint = authoredVisual(chapter);
  if (hint) {
    if (hint.evidence) {
      const item = evidenceById(packet.evidence, hint.evidence);
      return {
        kind: hint.kind || (item ? VISUAL_KIND_BY_EVIDENCE[item.kind] : 'card') || 'card',
        source: `evidence:${hint.evidence}`,
        label: hint.label || item?.label || null,
        ref: hint.ref || item?.ref || null,
        selector: hint.selector ?? null,
        zoom: hint.selector ? { selector: hint.selector } : hint.zoom ?? 'none',
      };
    }
    return {
      kind: hint.kind || (hint.url ? 'browser' : 'card'),
      source: hint.url ? `url:${hint.url}` : 'authored',
      label: hint.label || null,
      ref: hint.url || hint.ref || null,
      selector: hint.selector ?? null,
      zoom: hint.selector ? { selector: hint.selector } : hint.zoom ?? 'none',
    };
  }

  if (chapterId === 'decision') {
    return { kind: 'card', source: 'plan:decision', label: 'Decision', ref: null, selector: null, zoom: 'none' };
  }

  const items = chapterEvidence(chapterId, packet, language.prefer);
  if (items.length) {
    const item = items[0];
    return {
      kind: VISUAL_KIND_BY_EVIDENCE[item.kind] || 'card',
      source: `evidence:${item.id}`,
      label: item.label,
      ref: item.ref,
      selector: null,
      zoom: 'none',
    };
  }
  // No evidence for this chapter: a plan card carries it. The linter says so.
  return { kind: 'card', source: `plan:${chapterId}`, label: null, ref: null, selector: null, zoom: 'none' };
}

// --- narration ---------------------------------------------------------------

// Each builder returns { narration, sources }. `sources` are packet paths, and
// the linter resolves every one of them: that is the anti-invention check.
function buildContext(packet, style, visual) {
  const { plan } = packet;
  const lead = style.voice.lead;
  const sources = [];
  const parts = [lead.context];
  if (style.visuals.nameArtifact && visual.label && visual.source.startsWith('evidence:')) {
    parts.push(lead.onScreen(visual.label.replace(/[.]$/, '')));
    sources.push(visual.source);
  }
  const claims = (plan.currentState || []).filter((c) => (c.chapterId || 'context') === 'context');
  claims.forEach((c, i) => {
    parts.push(sentence(c.claim));
    const idx = (plan.currentState || []).indexOf(c);
    sources.push(`plan.currentState[${idx >= 0 ? idx : i}].claim`);
  });
  if (!claims.length) {
    // Nothing factual to say about the present. Speak the goal instead of
    // inventing a state, and let the linter tell the author what is missing.
    parts.push(sentence(plan.goal));
    sources.push('plan.goal');
  }
  return { narration: joinSentences(parts), sources };
}

function buildOutcome(packet, style) {
  const lead = style.voice.lead;
  return {
    narration: joinSentences([lead.outcome, sentence(packet.plan.outcome)]),
    sources: ['plan.outcome'],
  };
}

function buildApproach(packet, style, visual) {
  const { plan } = packet;
  const lead = style.voice.lead;
  const steps = plan.approach || [];
  const sources = [];
  const parts = [lead.approach(steps.length)];
  if (style.visuals.nameArtifact && visual.label && visual.source.startsWith('evidence:')) {
    parts.push(lead.onScreen(visual.label.replace(/[.]$/, '')));
    sources.push(visual.source);
  }
  steps.forEach((s, i) => {
    parts.push(lead.step(i + 1));
    parts.push(sentence(s.summary));
    sources.push(`plan.approach[${i}].summary`);
  });
  return { narration: joinSentences(parts), sources };
}

function buildRisks(packet, style) {
  const { plan } = packet;
  const lead = style.voice.lead;
  const sources = [];
  const parts = [lead.risks];
  (plan.risks || []).forEach((r, i) => {
    parts.push(sentence(r));
    sources.push(`plan.risks[${i}]`);
  });
  if ((plan.assumptions || []).length) {
    parts.push(lead.assumptions);
    plan.assumptions.forEach((a, i) => {
      parts.push(sentence(a));
      sources.push(`plan.assumptions[${i}]`);
    });
  }
  parts.push(lead.alternatives);
  if ((plan.alternatives || []).length) {
    plan.alternatives.forEach((alt, i) => {
      parts.push(sentence(alt.summary));
      sources.push(`plan.alternatives[${i}].summary`);
      if ((alt.tradeoffs || []).length) parts.push(lead.tradeoffs);
      (alt.tradeoffs || []).forEach((t, j) => {
        parts.push(sentence(t));
        sources.push(`plan.alternatives[${i}].tradeoffs[${j}]`);
      });
    });
  } else {
    parts.push(sentence(plan.noAlternativesReason));
    sources.push('plan.noAlternativesReason');
  }
  return { narration: joinSentences(parts), sources };
}

function buildDecision(packet, style) {
  const { plan } = packet;
  const lead = style.voice.lead;
  const options = plan.decision?.options || [];
  const alternatives = plan.alternatives || [];
  return {
    narration: joinSentences([
      lead.decision,
      sentence(plan.decision?.prompt),
      optionsSentence(lead.options, options, alternatives),
    ]),
    sources: ['plan.decision.prompt', 'plan.decision.options'],
  };
}

const BUILDERS = {
  context: buildContext,
  outcome: buildOutcome,
  approach: buildApproach,
  risks: buildRisks,
  decision: buildDecision,
};

const DEFAULT_TITLES = {
  context: 'What exists today',
  outcome: 'What changes',
  approach: 'How we build it',
  risks: 'What could go wrong',
  decision: 'What we need from you',
};

// --- the script ---------------------------------------------------------------

/**
 * Build plan.script.json from a validated packet.
 * Pure and deterministic: the same packet plus style always serializes to the
 * same bytes. Throws only on a style that does not exist.
 *
 * @param {{plan: object, evidence?: object|null}} packet
 * @param {{voice: object, visuals: object}} style — from resolveStyle()
 */
export function generatePlanScript(packet, style) {
  const { plan } = packet;
  const declared = Array.isArray(plan.chapters) && plan.chapters.length ? plan.chapters : null;
  const order = declared ? declared.map((c) => c.id) : CHAPTER_IDS;

  const chapters = order.map((id) => {
    const authored = declared ? declared.find((c) => c.id === id) : null;
    const visual = resolveVisual(id, authored, packet, style.visuals);
    const built = BUILDERS[id]({ ...packet }, style, visual);
    const chapter = {
      id,
      title: authored?.title || DEFAULT_TITLES[id],
      narration: built.narration,
      words: countWords(built.narration),
      estimatedSeconds: estimateSeconds(built.narration),
      visual,
      sources: built.sources,
      // The live control protocol's POST /step body, verbatim: one artifact
      // drives both the scripted and the live authoring path. `chapterId` is
      // what maps the recorded step back to this chapter; the name is free to
      // change without breaking the mapping.
      step: { name: id, chapterId: id, narration: built.narration, zoom: visual.zoom },
    };
    if (id === 'decision') {
      chapter.card = {
        type: plan.decision?.type ?? null,
        prompt: plan.decision?.prompt ?? null,
        options: (plan.decision?.options || []).map((o) => ({
          id: o,
          label: optionLabel(o, plan.alternatives || []),
        })),
      };
    }
    return chapter;
  });

  return {
    version: SCRIPT_VERSION,
    kind: 'plan-script',
    generator: 'deterministic',
    goal: plan.goal,
    voice: {
      profile: style.voice.id,
      instructions: style.voice.instructions,
    },
    visualLanguage: style.visuals.id,
    estimatedSeconds: round1(chapters.reduce((sum, c) => sum + c.estimatedSeconds, 0)),
    chapters,
  };
}

// --- quality lint --------------------------------------------------------------

// Resolve a packet path like `plan.approach[0].summary` or `evidence:ev-1`.
// Returns undefined when the path names nothing — which is what makes an
// invented source detectable.
function resolveSource(path, packet) {
  if (path.startsWith('evidence:')) {
    return evidenceById(packet.evidence, path.slice('evidence:'.length)) || undefined;
  }
  if (!path.startsWith('plan.')) return undefined;
  let node = packet.plan;
  for (const seg of path.slice('plan.'.length).split('.')) {
    const m = seg.match(/^([a-zA-Z]+)((?:\[\d+\])*)$/);
    if (!m || node == null) return undefined;
    node = node[m[1]];
    for (const idx of m[2].match(/\d+/g) || []) {
      if (!Array.isArray(node)) return undefined;
      node = node[Number(idx)];
    }
  }
  return node;
}

/**
 * Quality-lint a generated script against the packet it came from.
 * Returns { ok, errors, warnings } of { path, code, message } — the same shape
 * the packet validator uses, so `spool lint` reports both the same way.
 *
 * A generation failure must be diagnosable from this report alone, so every
 * message names the chapter and what to change.
 */
export function lintPlanScript(script, packet) {
  const errors = [];
  const warnings = [];
  const error = (path, code, message) => errors.push({ path, code, message });
  const warn = (path, code, message) => warnings.push({ path, code, message });

  if (!script || typeof script !== 'object') {
    error('', 'invalid-type', 'plan.script.json must be a JSON object');
    return { ok: false, errors, warnings };
  }
  if (script.version !== SCRIPT_VERSION) {
    error('version', 'unsupported-version', `plan.script.json declares version ${script.version}; this CLI reads ${SCRIPT_VERSION}. Regenerate it with \`spool plan generate\`.`);
    return { ok: false, errors, warnings };
  }

  const chapters = Array.isArray(script.chapters) ? script.chapters : [];
  const ids = chapters.map((c) => c.id);

  for (const id of REQUIRED_CHAPTERS) {
    if (!ids.includes(id)) {
      error('chapters', 'missing-chapter', `no "${id}" chapter: a plan must show context, approach, risks and a decision. Add {"id": "${id}"} to plan.json chapters.`);
    }
  }
  if (chapters.length < CHAPTER_MIN) {
    error('chapters', 'too-few-chapters', `${chapters.length} chapter(s); a plan spool needs ${CHAPTER_MIN} to ${CHAPTER_MAX}.`);
  }
  if (chapters.length > CHAPTER_MAX) {
    error('chapters', 'too-many-chapters', `${chapters.length} chapters; a plan spool needs ${CHAPTER_MIN} to ${CHAPTER_MAX}. Merge the narrow ones in plan.json chapters.`);
  }

  // Over-length breaks the format's promise (a reviewer opens a plan spool
  // expecting under two minutes), so it fails. Under-length is a thin plan the
  // author may knowingly accept, so it warns.
  const total = script.estimatedSeconds;
  if (typeof total === 'number' && total > DURATION_MAX_SECONDS) {
    error('estimatedSeconds', 'too-long', `the outline reads for about ${total}s; the format is ${DURATION_MIN_SECONDS} to ${DURATION_MAX_SECONDS}s. Shorten the approach summaries or split the plan.`);
  }
  if (typeof total === 'number' && total < DURATION_MIN_SECONDS) {
    warn('estimatedSeconds', 'too-short', `the outline reads for about ${total}s, under the ${DURATION_MIN_SECONDS}s target. Add currentState claims or risk detail so the reviewer can judge it.`);
  }

  chapters.forEach((c, i) => {
    const at = `chapters[${i}]`;
    if (!c.narration || !String(c.narration).trim()) {
      error(`${at}.narration`, 'empty-narration', `chapter "${c.id}" has no narration.`);
    }
    if (String(c.narration || '').includes(EM_DASH)) {
      warn(`${at}.narration`, 'em-dash', `chapter "${c.id}" narration contains an em dash; TTS reads it as a stumble. Use a full stop.`);
    }
    if (c.words > WORDS_PER_CHAPTER_MAX) {
      warn(`${at}.narration`, 'chapter-too-long', `chapter "${c.id}" is ${c.words} words (~${c.estimatedSeconds}s) on one visual; split it or trim the source text.`);
    }
    if (c.words && c.words < WORDS_PER_CHAPTER_MIN) {
      warn(`${at}.narration`, 'chapter-too-short', `chapter "${c.id}" is ${c.words} words; it will flash past the reviewer.`);
    }
    if (!c.visual || !c.visual.kind) {
      error(`${at}.visual`, 'missing-visual', `chapter "${c.id}" has no visual source; every chapter must show something.`);
    } else if (c.visual.source === `plan:${c.id}` && c.id !== 'decision') {
      warn(`${at}.visual`, 'no-evidence-visual', `chapter "${c.id}" shows a plan card because no evidence names it; add "chapterIds": ["${c.id}"] to an evidence descriptor.`);
    }

    // A context chapter built from the goal means the plan never said what
    // exists today, so the reviewer cannot check the premise.
    if (c.id === 'context' && (c.sources || []).includes('plan.goal')) {
      warn(`${at}.narration`, 'thin-context', 'the context chapter falls back to the goal because plan.json has no currentState claims; add what exists today.');
    }

    // The anti-invention check: every sentence the generator emitted must trace
    // back to something the author supplied.
    const sources = Array.isArray(c.sources) ? c.sources : [];
    if (!sources.length) {
      error(`${at}.sources`, 'unsourced-chapter', `chapter "${c.id}" records no source; a claim with no packet path cannot be trusted.`);
    }
    sources.forEach((src, j) => {
      const value = resolveSource(src, packet);
      if (value === undefined || value === null || (typeof value === 'string' && !value.trim())) {
        error(`${at}.sources[${j}]`, 'invented-source', `chapter "${c.id}" cites "${src}", which resolves to nothing in the packet. The generator must not invent claims or evidence.`);
      }
    });
    if (c.visual?.source?.startsWith('evidence:')) {
      const id = c.visual.source.slice('evidence:'.length);
      if (!evidenceById(packet.evidence, id)) {
        error(`${at}.visual.source`, 'unknown-evidence', `chapter "${c.id}" shows evidence "${id}", which is not declared in evidence.json.`);
      }
    }
  });

  const decision = chapters.find((c) => c.id === 'decision');
  if (decision) {
    const card = decision.card;
    if (!card || !card.prompt || !Array.isArray(card.options) || !card.options.length) {
      error('chapters.decision.card', 'missing-decision-card', 'the decision chapter has no decision card; the reviewer would have nothing to act on.');
    } else if (card.prompt !== packet.plan?.decision?.prompt) {
      error('chapters.decision.card.prompt', 'decision-drift', 'the decision card does not match plan.json decision.prompt. Regenerate with `spool plan generate`.');
    } else {
      const planOptions = packet.plan?.decision?.options || [];
      const cardOptions = card.options.map((o) => o.id);
      if (planOptions.join(' ') !== cardOptions.join(' ')) {
        error('chapters.decision.card.options', 'decision-drift', 'the decision card options do not match plan.json decision.options. Regenerate with `spool plan generate`.');
      }
    }
  }

  return { ok: errors.length === 0, errors, warnings };
}

// --- emitters ------------------------------------------------------------------

const js = (v) => JSON.stringify(v);

// One step per chapter. The driver body only does what the visual actually
// asks for: a browser visual navigates and settles, everything else holds the
// frame for the plan card (R2.2 renders those).
function stepBody(chapter, configUrl) {
  const lines = [];
  const v = chapter.visual || {};
  lines.push(`      // ${v.kind} visual${v.ref ? `: ${v.ref}` : ''}${v.label ? ` (${v.label})` : ''}`);
  if (v.kind === 'browser' && v.ref && v.ref !== configUrl) {
    lines.push(`      await page.goto(${js(v.ref)});`);
  }
  if (v.selector) {
    lines.push(`      await page.waitForSelector(${js(v.selector)});`);
    lines.push(`      await h.hover(${js(v.selector)});`);
  }
  const hold = Math.max(900, Math.round(chapter.estimatedSeconds * 1000));
  lines.push(`      await h.pause(${hold});`);
  return lines.join('\n');
}

/**
 * Emit a scripted steps.mjs for a generated script.
 * The renderer retimes each step to its narration, so the holds here only need
 * to keep the page settled for the length of the take.
 */
export function renderStepsModule(script, { url, title, format } = {}) {
  if (!url) throw new Error('renderStepsModule: url required (pass --url or keep an existing steps.mjs config.url)');
  const head = [
    `// ${STEPS_MARKER} — one step per plan chapter, each anchored by chapterId.`,
    '// Regenerate after editing plan.json; edit narration here only for a one-off take',
    '// (plan.json stays the source of truth, see CONTRACTS.md "Plan Spools").',
    '',
    'export const config = {',
    `  url: ${js(url)},`,
    '  viewport: { width: 1600, height: 900 },',
    `  title: ${js(title || script.goal)},`,
    ...(format ? [`  format: ${js(format)},`] : []),
    '  prep: async (page, h) => {},',
    '};',
    '',
    'export const steps = [',
  ];
  const body = script.chapters.map((c) => [
    '  {',
    `    name: ${js(c.id)},`,
    `    chapterId: ${js(c.id)},`,
    `    narration: ${js(c.narration)},`,
    `    zoom: ${js(c.visual?.zoom ?? 'none')},`,
    '    run: async (page, h) => {',
    stepBody(c, url),
    '    },',
    '  },',
  ].join('\n'));
  return [...head, ...body, '];', ''].join('\n');
}

/** Terse human report of a generated script, for the CLI. */
export function formatScript(script) {
  const lines = [
    `plan script: ${script.chapters.length} chapters, ~${script.estimatedSeconds}s ` +
      `(voice: ${script.voice.profile}, visuals: ${script.visualLanguage}${script.generator === 'llm-refined' ? ', llm-refined' : ''})`,
  ];
  for (const c of script.chapters) {
    const where = c.visual?.ref || c.visual?.label || c.visual?.source || '';
    lines.push(`  ${c.id.padEnd(9)} ${String(c.estimatedSeconds).padStart(5)}s  ${(c.visual?.kind || '?').padEnd(8)} ${where}`);
  }
  return lines.join('\n');
}

// --- workdir I/O -----------------------------------------------------------------

export function scriptPath(workdir) {
  return join(resolve(workdir), SCRIPT_FILE);
}

/** Read plan.script.json from a workdir, or null when it has none. */
export async function readPlanScript(workdir) {
  const p = scriptPath(workdir);
  if (!existsSync(p)) return null;
  try {
    return JSON.parse(await readFile(p, 'utf8'));
  } catch {
    return null;
  }
}

/** The approved voice direction for `spool vo`, or null when there is no script. */
export async function planVoiceInstructions(workdir) {
  const script = await readPlanScript(workdir);
  return script?.voice?.instructions || null;
}

export async function writePlanScript(workdir, script) {
  const p = scriptPath(workdir);
  await writeFile(p, JSON.stringify(script, null, 2) + '\n');
  return p;
}

/**
 * Write steps.mjs for a generated script. Refuses to clobber a file this
 * generator did not write (a hand-authored script or a live take's snapshot)
 * unless `force` is set.
 */
export async function writeStepsModule(workdir, script, { url, title, format, force = false } = {}) {
  const p = join(resolve(workdir), 'steps.mjs');
  if (existsSync(p) && !force) {
    const current = await readFile(p, 'utf8');
    if (!current.includes(STEPS_MARKER)) {
      throw new Error(`${p} was not written by \`spool plan generate\` (hand-authored or a live snapshot). Pass --force to overwrite it.`);
    }
  }
  await writeFile(p, renderStepsModule(script, { url, title, format }));
  return p;
}

/** config.url of an existing steps.mjs, without importing it (no side effects). */
export async function existingStepsUrl(workdir) {
  const p = join(resolve(workdir), 'steps.mjs');
  if (!existsSync(p)) return null;
  const m = (await readFile(p, 'utf8')).match(/url:\s*(['"])(.*?)\1/);
  return m ? m[2] : null;
}
